export 'package:allesc/pages/candidatura_page.dart';
export 'package:allesc/pages/comprobar_auth_page.dart';
export 'package:allesc/pages/graficos_page.dart';
export 'package:allesc/pages/login_page.dart';
export 'package:allesc/pages/main_page.dart';
export 'package:allesc/pages/register_page.dart';
export 'package:allesc/pages/paises_page.dart';
export 'package:allesc/pages/resultados_page.dart';
export 'package:allesc/pages/votar_page.dart';
